name: "Docusaurus Blogs Changes to Work-WeChat Action"
description: "Detect Docusaurus blogs changes and send notifications to WeChat Robot"
author: "TinyFunction"

inputs:
  wechat_webhook:
    description: "The webhook URL for your Work-WeChat robot"
    required: true
  base_url:
    description: "The base URL of your GitHub Pages site"
    required: true
  blog_dir:
    description: "The directory where your blog posts are stored"
    default: "blog"
    required: false

runs:
  using: "node20" # 使用 Node.js 运行环境
  main: "dist/index.js" # 指向编译后的主脚本文件

branding:
  icon: "send" # 图标
  color: "green" # 颜色